In [ ]:
'''
Numpy:
    -> fundamental library for scientific computing in Python
    -> provides support for arrays and matrices along with a collection of mathematical
        functions to operate on these data structures
'''



In [1]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.shape # since 1 dimension with 4 elements (4,)

(4,)

In [6]:
# 2- Dimensional
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [9]:
arr2 = np.array([[1,2,3,4,5,6]])
arr2.shape

(1, 6)

In [13]:
# N- d arrays
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]]
(3, 5)


In [19]:
# Create array with inbuilt functions
# function - arange and reshape it to 1d
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [25]:
#inbuilt fnction for deep learning with creating n size arrays
# functions: ones, zeroes
# parameters: (rows, columns)
print('Ones')
print(np.ones((3,4)))
print('\nZeroes')
print(np.zeros((4,5)))


Ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Zeroes
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
# Identity matrix
# all diagonal elements will be 1'set
# parameter = number of arrays 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
#Summary to get the details of arrays
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:", arr.shape)
print("Number of dimenstions", arr.ndim)
print("Size(No of elements)", arr.size)
print("Data Type: ",arr.dtype)
print("Item size in bytes: ", arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimenstions 2
Size(No of elements) 6
Data Type:  int64
Item size in bytes:  8


In [34]:
# Numpy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element wise addition
print("Addition:", arr1+arr2)

#Element wise substraction
print("Substraction:", arr1-arr2)

#Element wise multiply
print("Multiply:", arr1*arr2)

#Element wise division
print("Division:", arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiply: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
# Universal function
# function which is apply to all the arrays
arr1 = np.array([1,2,3,4,5])
#sqrt
print(np.sqrt(arr))
#exponential
print(np.exp(arr1))
#Sine
print(np.sin(arr))
#Log
print(np.log(arr))


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [ ]:
# Array 
# Slicing and Indexing
arr = np.array([[1,2,4,5,6],[7,8,9,0,11],[12,13,14,15,16]])
print(arr)

[[ 1  2  4  5  6]
 [ 7  8  9  0 11]
 [12 13 14 15 16]]


In [ ]:
#picking up the element from specific index
arr[0][4]

np.int64(6)

In [49]:
#picking up the whole rows
arr[1:]

array([[ 7,  8,  9,  0, 11],
       [12, 13, 14, 15, 16]])

In [50]:
#picking up the rows and cols
arr[1:,2:]

array([[ 9,  0, 11],
       [14, 15, 16]])

In [51]:
#read 1st and 2nd column, and get last 2 columns
print(arr[0:2,2:])

[[ 4  5  6]
 [ 9  0 11]]


In [52]:
# modify elements
arr[0,0]=100
print(arr)

[[100   2   4   5   6]
 [  7   8   9   0  11]
 [ 12  13  14  15  16]]


In [53]:
arr[1:]=100
print(arr)

[[100   2   4   5   6]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [54]:
# Statistics Concept
'''
Normalization
-> to have mean of 0 and standard deviation at 1
'''
data = np.array([1,2,3,4,5])

#compute mean and std dev
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data
normalized_data = (data-mean)/std_dev
print(normalized_data)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [55]:
#Basic Stats 
print("Mean: ", np.mean(data))
print("Median: ", np.median(data))
print("Std Dev: ", np.std(data))
print("Variance: ", np.var(data))


Mean:  3.0
Median:  3.0
Std Dev:  1.4142135623730951
Variance:  2.0


In [5]:
# Logical Ops
data = np.array([1,2,4,5,6,7,10,8,9])
print(data>=5)
print(data[data>5])
print(data[(data>5) & (data<9)])

[False False False  True  True  True  True  True  True]
[ 6  7 10  8  9]
[6 7 8]
